[build.environment]
GO_VERSION = "1.22.2"
HUGO_VERSION = "0.147.8"
NODE_VERSION = "22"
TZ = "Europe/Warsaw"

[build]
publish = "public"
command = "git config core.quotepath false && hugo --gc --minify --config config.prod.yaml"